name: LunaticLib
version:  '${project.version}'
main: de.janschuri.lunaticlib.platform.bukkit.BukkitLunaticLib
api-version: '1.19'
author: Janschuri
description: A Library for Lunatic plugins.
softdepend:
  - Vault
  - LogBlock
