rootProject.name = "lunaticlib"

include(":lunaticlib-api")
include(":lunaticlib-config")
include(":lunaticlib-utils")
include(":lunaticlib-utils-paper")
include(":lunaticlib-inventorygui")
include(":lunaticlib-sender")
include(":lunaticlib-sender-paper")
include(":lunaticlib-sender-velocity")
include(":lunaticlib-sender-waterfall")
include(":lunaticlib-commands")
include(":lunaticlib-commands-paper")
include(":lunaticlib-commands-velocity")
include(":lunaticlib-commands-waterfall")
include(":lunaticlib-proxyrequests")
include(":lunaticlib-proxyrequests-paper")
include(":lunaticlib-proxyrequests-waterfall")
include(":lunaticlib-proxyrequests-velocity")
include("lunaticlib-sender")
include("lunaticlib-paper")
include("lunaticlib-velocity")
include("lunaticlib-waterfall")
